CREATE TABLE USER_PROFILE { 
    ID BIGINT NOT NULL AUTO_INCREMENT;
    USERNAME VARCHAR(255) NOT NULL;
    LASTNAME VARCHAR(255) NOT NULL;
    PASSWORD VARCHAR(255) NOT NULL;
    PASSWORDCONFIRM VARCHAR(255) NOT NULL;
    EMAIL VARCHAR(255) NOT NULL;
    DATEOFBIRTH VARCHAR(255);
    MED_ID BIGINT NOT NULL; 
    PRIMARY KEY (ID);
    
};